export const dom = {
    outputCanvas: document.getElementById('output-canvas'),
    outputPanel: document.getElementById('output-panel'),
    outputMeta: document.getElementById('output-meta'),
    outputWrapper: document.getElementById('output-wrapper'),
    renderOverlay: document.getElementById('render-overlay'),
    progressWrap: document.getElementById('progress-wrap'),
    progressFill: document.getElementById('progress-fill'),
    progressText: document.getElementById('progress-text'),
    preprocessProgressWrap: document.getElementById('preprocess-progress-wrap'),
    preprocessProgressFill: document.getElementById('preprocess-progress-fill'),
    preprocessProgressText: document.getElementById('preprocess-progress-text'),
    btnPreprocess: document.getElementById('btn-preprocess'),
    btnGenerate: document.getElementById('btn-generate'),
    btnStop: document.getElementById('btn-stop'),
    btnDownload: document.getElementById('btn-download'),
    bannerDirty: document.getElementById('banner-dirty'),
    preprocessStatus: document.getElementById('preprocess-status'),
    pixelSizeEl: document.getElementById('pixel-size'),
    tileSizeEl: document.getElementById('tile-size'),
    infoPxEl: document.getElementById('info-pixel'),
    infoTileEl: document.getElementById('info-tile'),
    mainDropInner: document.getElementById('main-drop-inner'),
    inputMain: document.getElementById('input-main'),
};
