export const sineDom = {
    inputMain: document.getElementById('sine-input-main'),
    drop: document.getElementById('sine-drop'),
    dropInner: document.getElementById('sine-drop-inner'),
    statusDot: document.getElementById('sine-sd-main'),
    readinessItem: document.getElementById('sine-ri-main'),
    btnGenerate: document.getElementById('sine-btn-generate'),
    btnStop: document.getElementById('sine-btn-stop'),
    btnDownload: document.getElementById('sine-btn-download'),
    progressWrap: document.getElementById('sine-progress-wrap'),
    progressFill: document.getElementById('sine-progress-fill'),
    progressText: document.getElementById('sine-progress-text'),
    outputPanel: document.getElementById('sine-output-panel'),
    outputMeta: document.getElementById('sine-output-meta'),
    outputWrapper: document.getElementById('sine-output-wrapper'),
    outputCanvas: document.getElementById('sine-output-canvas'),
    renderOverlay: document.getElementById('sine-render-overlay'),
    gridInfo: document.getElementById('sine-info-grid'),
    outputInfo: document.getElementById('sine-info-output'),
};
